last_change = 2024-12-26T02:50:09.329170Z
addr = 0xbfb76
size = 0x2a
name = "__set_printf_count_output"
artifact_type = "Function"

[header]
name = "__set_printf_count_output"
addr = 0xbfb76

[header.args]
