last_change = 2024-12-26T02:50:09.329170Z
addr = 0xbaf48
size = 0x4b
name = "`eh_vector_destructor_iterator'"
artifact_type = "Function"

[header]
name = "`eh_vector_destructor_iterator'"
addr = 0xbaf48

[header.args]
