last_change = 2024-12-26T02:50:09.329170Z
addr = 0xbec8b
size = 0x23
name = "FID_conflict:__sscanf_s_l"
artifact_type = "Function"

[header]
name = "FID_conflict:__sscanf_s_l"
addr = 0xbec8b

[header.args]
