last_change = 2024-12-26T02:50:09.329170Z
addr = 0xbb34b
size = 0x21
name = "__invoke_watson_if_error"
artifact_type = "Function"

[header]
name = "__invoke_watson_if_error"
addr = 0xbb34b

[header.args]
