last_change = 2024-12-26T02:50:09.329170Z
addr = 0xb1970
size = 0x22
name = "EnlargedUnsignedDivide"
artifact_type = "Function"

[header]
name = "EnlargedUnsignedDivide"
addr = 0xb1970

[header.args]
