last_change = 2024-12-26T02:50:09.330171Z
addr = 0xc89b2
size = 0x1c
name = "FID_conflict:__vscprintf_p"
artifact_type = "Function"

[header]
name = "FID_conflict:__vscprintf_p"
addr = 0xc89b2

[header.args]
