last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc5bb0
size = 0x13
name = "FID_conflict:_iswpunct"
artifact_type = "Function"

[header]
name = "FID_conflict:_iswpunct"
addr = 0xc5bb0

[header.args]
