last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc5aec
size = 0x13
name = "FID_conflict:__iswupper_l"
artifact_type = "Function"

[header]
name = "FID_conflict:__iswupper_l"
addr = 0xc5aec

[header.args]
