last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc5ad6
size = 0x16
name = "FID_conflict:_iswalpha"
artifact_type = "Function"

[header]
name = "FID_conflict:_iswalpha"
addr = 0xc5ad6

[header.args]
