last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc1bb3
size = 0x73
name = "_GetRangeOfTrysToCheck"
artifact_type = "Function"

[header]
name = "_GetRangeOfTrysToCheck"
addr = 0xc1bb3

[header.args]
