last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc167b
size = 0x26
name = "____lc_collate_cp_func"
artifact_type = "Function"

[header]
name = "____lc_collate_cp_func"
addr = 0xc167b

[header.args]
