last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc5bec
size = 0x16
name = "FID_conflict:_iswalnum"
artifact_type = "Function"

[header]
name = "FID_conflict:_iswalnum"
addr = 0xc5bec

[header.args]
