last_change = 2024-12-26T02:50:09.330171Z
addr = 0xcc702
size = 0x1f1
name = "___get_qualified_locale"
artifact_type = "Function"

[header]
name = "___get_qualified_locale"
addr = 0xcc702

[header.args]
