last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc5c2e
size = 0x16
name = "FID_conflict:__iswgraph_l"
artifact_type = "Function"

[header]
name = "FID_conflict:__iswgraph_l"
addr = 0xc5c2e

[header.args]
