last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc0c9b
size = 0x2a
name = "FID_conflict:__vswprintf_p_l"
artifact_type = "Function"

[header]
name = "FID_conflict:__vswprintf_p_l"
addr = 0xc0c9b

[header.args]
