last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc258b
size = 0x1c
name = "FID_conflict:__vscprintf_p"
artifact_type = "Function"

[header]
name = "FID_conflict:__vscprintf_p"
addr = 0xc258b

[header.args]
