last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc27e9
size = 0x20
name = "FID_conflict:__vfprintf_l"
artifact_type = "Function"

[header]
name = "FID_conflict:__vfprintf_l"
addr = 0xc27e9

[header.args]
