last_change = 2024-12-26T02:50:09.330171Z
addr = 0xc8b5d
size = 0x1d
name = "FID_conflict:__vwprintf_s_l"
artifact_type = "Function"

[header]
name = "FID_conflict:__vwprintf_s_l"
addr = 0xc8b5d

[header.args]
