last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc5b74
size = 0x16
name = "FID_conflict:__iswxdigit_l"
artifact_type = "Function"

[header]
name = "FID_conflict:__iswxdigit_l"
addr = 0xc5b74

[header.args]
