last_change = 2024-12-26T02:50:09.330171Z
addr = 0xcc65f
size = 0x67
name = "_GetLcidFromLangCountry"
artifact_type = "Function"

[header]
name = "_GetLcidFromLangCountry"
addr = 0xcc65f

[header.args]
