last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc5b4b
size = 0x13
name = "FID_conflict:__iswdigit_l"
artifact_type = "Function"

[header]
name = "FID_conflict:__iswdigit_l"
addr = 0xc5b4b

[header.args]
