last_change = 2024-12-26T02:50:09.330171Z
addr = 0xc5cba
size = 0x26
name = "FID_conflict:__iswcsym_l"
artifact_type = "Function"

[header]
name = "FID_conflict:__iswcsym_l"
addr = 0xc5cba

[header.args]
