last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc1c52
size = 0x27
name = "__IsExceptionObjectToBeDestroyed"
artifact_type = "Function"

[header]
name = "__IsExceptionObjectToBeDestroyed"
addr = 0xc1c52

[header.args]
