last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc5b25
size = 0x13
name = "FID_conflict:_iswlower"
artifact_type = "Function"

[header]
name = "FID_conflict:_iswlower"
addr = 0xc5b25

[header.args]
