last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc1b14
size = 0x16
name = "TranslatorGuardHandler"
artifact_type = "Function"

[header]
name = "TranslatorGuardHandler"
addr = 0xc1b14

[header.args]
