last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc24f6
size = 0x5c
name = "FID_conflict:__vscprintf_helper"
artifact_type = "Function"

[header]
name = "FID_conflict:__vscprintf_helper"
addr = 0xc24f6

[header.args]
