last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc4362
size = 0x42
name = "__get_errno_from_oserr"
artifact_type = "Function"

[header]
name = "__get_errno_from_oserr"
addr = 0xc4362

[header.args]
