last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc5c02
size = 0x16
name = "FID_conflict:_iswprint"
artifact_type = "Function"

[header]
name = "FID_conflict:_iswprint"
addr = 0xc5c02

[header.args]
