last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc5c5a
size = 0x13
name = "FID_conflict:_iswcntrl"
artifact_type = "Function"

[header]
name = "FID_conflict:_iswcntrl"
addr = 0xc5c5a

[header.args]
