last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc0e6b
size = 0x29
name = "FID_conflict:__vswprintf_c"
artifact_type = "Function"

[header]
name = "FID_conflict:__vswprintf_c"
addr = 0xc0e6b

[header.args]
