last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc5203
size = 0x4d
name = "__updatetlocinfoEx_nolock"
artifact_type = "Function"

[header]
name = "__updatetlocinfoEx_nolock"
addr = 0xc5203

[header.args]
