last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc25a7
size = 0x1d
name = "FID_conflict:__vscprintf_p_l"
artifact_type = "Function"

[header]
name = "FID_conflict:__vscprintf_p_l"
addr = 0xc25a7

[header.args]
