last_change = 2024-12-26T02:50:09.329170Z
addr = 0xc5b8a
size = 0x13
name = "FID_conflict:__iswspace_l"
artifact_type = "Function"

[header]
name = "FID_conflict:__iswspace_l"
addr = 0xc5b8a

[header.args]
