last_change = 2024-12-26T02:50:09.330171Z
addr = 0xc5d06
size = 0x26
name = "FID_conflict:___iswcsymf"
artifact_type = "Function"

[header]
name = "FID_conflict:___iswcsymf"
addr = 0xc5d06

[header.args]
