last_change = 2024-12-26T02:50:09.330171Z
addr = 0xd8ee5
size = 0x42
name = "__CxxUnhandledExceptionFilter"
artifact_type = "Function"

[header]
name = "__CxxUnhandledExceptionFilter"
addr = 0xd8ee5

[header.args]
