last_change = 2024-12-26T02:50:09.330171Z
addr = 0xddd67
size = 0x20d
name = "getTemplateArgumentList"
artifact_type = "Function"

[header]
name = "getTemplateArgumentList"
addr = 0xddd67

[header.args]
