last_change = 2024-12-26T02:50:09.330171Z
addr = 0xda548
size = 0xe6
name = "___InternalCxxFrameHandler"
artifact_type = "Function"

[header]
name = "___InternalCxxFrameHandler"
addr = 0xda548

[header.args]
