last_change = 2024-12-26T02:50:09.330171Z
addr = 0xdb752
size = 0x17
name = "@_EH4_CallFilterFunc@8"
artifact_type = "Function"

[header]
name = "@_EH4_CallFilterFunc@8"
addr = 0xdb752

[header.args]
