last_change = 2024-12-26T02:50:09.330171Z
addr = 0xda0af
size = 0x107
name = "FindHandlerForForeignException"
artifact_type = "Function"

[header]
name = "FindHandlerForForeignException"
addr = 0xda0af

[header.args]
