last_change = 2024-12-26T02:50:09.330171Z
addr = 0xd6b40
size = 0xa6
name = "__IsNonwritableInCurrentImage"
artifact_type = "Function"

[header]
name = "__IsNonwritableInCurrentImage"
addr = 0xd6b40

[header.args]
