last_change = 2024-12-26T02:50:09.330171Z
addr = 0xd5d6a
size = 0x2d
name = "__set_errno_from_matherr"
artifact_type = "Function"

[header]
name = "__set_errno_from_matherr"
addr = 0xd5d6a

[header.args]
