last_change = 2024-12-26T02:50:09.330171Z
addr = 0xd2bc3
size = 0x2c
name = "__invoke_watson_if_oneof"
artifact_type = "Function"

[header]
name = "__invoke_watson_if_oneof"
addr = 0xd2bc3

[header.args]
