last_change = 2024-12-26T02:50:09.330171Z
addr = 0xd936b
size = 0x9b
name = "___security_init_cookie"
artifact_type = "Function"

[header]
name = "___security_init_cookie"
addr = 0xd936b

[header.args]
