last_change = 2024-12-26T02:50:09.330171Z
addr = 0xdb769
size = 0x19
name = "@_EH4_TransferToHandler@8"
artifact_type = "Function"

[header]
name = "@_EH4_TransferToHandler@8"
addr = 0xdb769

[header.args]
