last_change = 2024-12-26T02:50:09.330171Z
addr = 0xdfd82
size = 0x3df
name = "getFunctionIndirectType"
artifact_type = "Function"

[header]
name = "getFunctionIndirectType"
addr = 0xdfd82

[header.args]
