last_change = 2024-12-26T02:50:09.330171Z
addr = 0xe0938
size = 0x20
name = "FID_conflict:getPointerType"
artifact_type = "Function"

[header]
name = "FID_conflict:getPointerType"
addr = 0xe0938

[header.args]
