last_change = 2024-12-26T02:50:09.331169Z
addr = 0xee017
size = 0x34
name = "_LStrxfrm<unsigned_short>"
artifact_type = "Function"

[header]
name = "_LStrxfrm<unsigned_short>"
addr = 0xee017

[header.args]
