last_change = 2024-12-26T02:50:09.331677Z
addr = 0xf896c
size = 0x1c
name = "FID_conflict:do_positive_sign"
artifact_type = "Function"

[header]
name = "FID_conflict:do_positive_sign"
addr = 0xf896c

[header.args]
