last_change = 2024-12-26T02:50:09.331677Z
addr = 0xfcad6
size = 0x9d
name = "use_facet<class_std::messages<char>_>"
artifact_type = "Function"

[header]
name = "use_facet<class_std::messages<char>_>"
addr = 0xfcad6

[header.args]
