last_change = 2024-12-26T02:50:09.331677Z
addr = 0xf5024
size = 0x15
name = "FID_conflict:operator+="
artifact_type = "Function"

[header]
name = "FID_conflict:operator+="
addr = 0xf5024

[header.args]
