last_change = 2024-12-26T02:50:09.331677Z
addr = 0xfcf4a
size = 0x33
name = "time_get<char,class_std::istreambuf_iterator<char,struct_std::char_traits<char>_>_>"
artifact_type = "Function"

[header]
name = "time_get<char,class_std::istreambuf_iterator<char,struct_std::char_traits<char>_>_>"
addr = 0xfcf4a

[header.args]
