last_change = 2024-12-26T02:50:09.331677Z
addr = 0x10d1a0
size = 0x4de
name = "gSpriteDraw_NaomiLibVersion"
artifact_type = "Function"

[header]
name = "gSpriteDraw_NaomiLibVersion"
addr = 0x10d1a0

[header.args]
