last_change = 2024-12-26T02:50:09.331677Z
addr = 0x1127e0
size = 0x5d2
name = "GraphicExecute_Player"
artifact_type = "Function"

[header]
name = "GraphicExecute_Player"
addr = 0x1127e0

[header.args]
