last_change = 2024-12-26T02:50:09.331677Z
addr = 0x1228d0
size = 0x149
name = "CmnAct_ThrowDMGPOEX2Land"
artifact_type = "Function"

[header]
name = "CmnAct_ThrowDMGPOEX2Land"
addr = 0x1228d0

[header.args]
