last_change = 2024-12-26T02:50:09.331677Z
addr = 0x122b00
size = 0x67
name = "CmnAct_ThrowDMGPOEX2Jump"
artifact_type = "Function"

[header]
name = "CmnAct_ThrowDMGPOEX2Jump"
addr = 0x122b00

[header.args]
