last_change = 2024-12-26T02:50:09.331677Z
addr = 0x122b70
size = 0x114
name = "CmnAct_ThrowDMGPOEXLand"
artifact_type = "Function"

[header]
name = "CmnAct_ThrowDMGPOEXLand"
addr = 0x122b70

[header.args]
