last_change = 2024-12-26T02:50:09.332678Z
addr = 0x12f5e0
size = 0x3ca
name = "HitEffKakuseiRingDraw"
artifact_type = "Function"

[header]
name = "HitEffKakuseiRingDraw"
addr = 0x12f5e0

[header.args]
