last_change = 2024-12-26T02:50:09.331677Z
addr = 0x122eb0
size = 0x68
name = "CmnAct_ThrowDMGFA_NAME"
artifact_type = "Function"

[header]
name = "CmnAct_ThrowDMGFA_NAME"
addr = 0x122eb0

[header.args]
