last_change = 2024-12-26T02:50:09.331677Z
addr = 0x122c90
size = 0x67
name = "CmnAct_ThrowDMGPOEXJump"
artifact_type = "Function"

[header]
name = "CmnAct_ThrowDMGPOEXJump"
addr = 0x122c90

[header.args]
