last_change = 2024-12-26T02:50:09.332678Z
addr = 0x13ce10
size = 0x3b
name = "IsTrgAndOffHeavySlash"
artifact_type = "Function"

[header]
name = "IsTrgAndOffHeavySlash"
addr = 0x13ce10

[header.args]
