last_change = 2024-12-26T02:50:09.332678Z
addr = 0x13e160
size = 0x76
name = "DirectDirectionKeyGet"
artifact_type = "Function"

[header]
name = "DirectDirectionKeyGet"
addr = 0x13e160

[header.args]
