last_change = 2024-12-26T02:50:09.332678Z
addr = 0x13b940
size = 0x36
name = "SearchEffectWorkActno"
artifact_type = "Function"

[header]
name = "SearchEffectWorkActno"
addr = 0x13b940

[header.args]
