last_change = 2024-12-26T02:50:09.332678Z
addr = 0x13b900
size = 0x36
name = "SearchObjectWorkActno"
artifact_type = "Function"

[header]
name = "SearchObjectWorkActno"
addr = 0x13b900

[header.args]
