last_change = 2024-12-26T02:50:09.332678Z
addr = 0x14bc90
size = 0x46c
name = "CharPosCollisionExecute"
artifact_type = "Function"

[header]
name = "CharPosCollisionExecute"
addr = 0x14bc90

[header.args]
