last_change = 2024-12-26T02:50:09.332678Z
addr = 0x1f3c10
size = 0x12
name = "CmnAct_StandLowDamage2"
artifact_type = "Function"

[header]
name = "CmnAct_StandLowDamage2"
addr = 0x1f3c10

[header.args]
