last_change = 2024-12-26T02:50:09.332678Z
addr = 0x1f4060
size = 0x2b7
name = "CmnAct_HeavyGroundHit"
artifact_type = "Function"

[header]
name = "CmnAct_HeavyGroundHit"
addr = 0x1f4060

[header.args]
