last_change = 2024-12-26T02:50:09.332678Z
addr = 0x1f2e50
size = 0x13
name = "CmnAct_StandHeavySlash"
artifact_type = "Function"

[header]
name = "CmnAct_StandHeavySlash"
addr = 0x1f2e50

[header.args]
