last_change = 2024-12-26T02:50:09.332678Z
addr = 0x1f36b0
size = 0x16e
name = "CmnAct_StdDmg_ToStand"
artifact_type = "Function"

[header]
name = "CmnAct_StdDmg_ToStand"
addr = 0x1f36b0

[header.args]
