last_change = 2024-12-26T02:50:09.332678Z
addr = 0x1f53a0
size = 0x17d
name = "CmnAct_JumpDash_Forward"
artifact_type = "Function"

[header]
name = "CmnAct_JumpDash_Forward"
addr = 0x1f53a0

[header.args]
