last_change = 2024-12-26T02:50:09.332678Z
addr = 0x1f5980
size = 0x16
name = "CmnAct_ForwardDownBound"
artifact_type = "Function"

[header]
name = "CmnAct_ForwardDownBound"
addr = 0x1f5980

[header.args]
