last_change = 2024-12-26T02:50:09.332678Z
addr = 0x1f3bd0
size = 0x12
name = "CmnAct_StandLowDamage3"
artifact_type = "Function"

[header]
name = "CmnAct_StandLowDamage3"
addr = 0x1f3bd0

[header.args]
