last_change = 2024-12-26T02:50:09.332678Z
addr = 0x1f2e70
size = 0x13
name = "CmnAct_StandCloseSlash"
artifact_type = "Function"

[header]
name = "CmnAct_StandCloseSlash"
addr = 0x1f2e70

[header.args]
