last_change = 2024-12-26T02:50:09.332678Z
addr = 0x1f18f0
size = 0x50
name = "CmnAct_StandTurnRight"
artifact_type = "Function"

[header]
name = "CmnAct_StandTurnRight"
addr = 0x1f18f0

[header.args]
