last_change = 2024-12-26T02:50:09.332678Z
addr = 0x221350
size = 0x3c4
name = "lpTopLevelExceptionFilter_00621350"
artifact_type = "Function"

[header]
name = "lpTopLevelExceptionFilter_00621350"
addr = 0x221350

[header.args]
