last_change = 2024-12-26T02:50:09.332678Z
addr = 0x24ff10
size = 0x46
name = "EXSolAct_FBGrandViperLand"
artifact_type = "Function"

[header]
name = "EXSolAct_FBGrandViperLand"
addr = 0x24ff10

[header.args]
