last_change = 2024-12-26T02:50:09.332678Z
addr = 0x253400
size = 0xb2
name = "SolAct_VolcanicViperDrop"
artifact_type = "Function"

[header]
name = "SolAct_VolcanicViperDrop"
addr = 0x253400

[header.args]
