last_change = 2024-12-26T02:50:09.332678Z
addr = 0x2501d0
size = 0x52
name = "EXSolAct_BanditRevolver1"
artifact_type = "Function"

[header]
name = "EXSolAct_BanditRevolver1"
addr = 0x2501d0

[header.args]
