last_change = 2024-12-26T02:50:09.332678Z
addr = 0x251f70
size = 0x5e
name = "SolAct_ggxGrandViperJump"
artifact_type = "Function"

[header]
name = "SolAct_ggxGrandViperJump"
addr = 0x251f70

[header.args]
