last_change = 2024-12-26T02:50:09.332678Z
addr = 0x251430
size = 0x13b
name = "SolAct_DragonInstallEnd"
artifact_type = "Function"

[header]
name = "SolAct_DragonInstallEnd"
addr = 0x251430

[header.args]
