last_change = 2024-12-26T02:50:09.332678Z
addr = 0x250230
size = 0x4d
name = "EXSolAct_FlameDipperSweep"
artifact_type = "Function"

[header]
name = "EXSolAct_FlameDipperSweep"
addr = 0x250230

[header.args]
