last_change = 2024-12-26T02:50:09.332678Z
addr = 0x250430
size = 0x57
name = "EXSolAct_AirGunflameH"
artifact_type = "Function"

[header]
name = "EXSolAct_AirGunflameH"
addr = 0x250430

[header.args]
