last_change = 2024-12-26T02:50:09.332678Z
addr = 0x251da0
size = 0x46
name = "SolAct_BanditRevolverLand"
artifact_type = "Function"

[header]
name = "SolAct_BanditRevolverLand"
addr = 0x251da0

[header.args]
