last_change = 2024-12-26T02:50:09.332678Z
addr = 0x252470
size = 0x5e
name = "SolAct_AirSuperVolcanicViperH"
artifact_type = "Function"

[header]
name = "SolAct_AirSuperVolcanicViperH"
addr = 0x252470

[header.args]
