last_change = 2024-12-26T02:50:09.332678Z
addr = 0x2522c0
size = 0x4c
name = "SolAct_DIVolcanicViper"
artifact_type = "Function"

[header]
name = "SolAct_DIVolcanicViper"
addr = 0x2522c0

[header.args]
