last_change = 2024-12-26T02:50:09.332678Z
addr = 0x2505d0
size = 0x66
name = "SolAct_SavageGunflame"
artifact_type = "Function"

[header]
name = "SolAct_SavageGunflame"
addr = 0x2505d0

[header.args]
