last_change = 2024-12-26T02:50:09.332678Z
addr = 0x2525e0
size = 0x53
name = "SolAct_VolcanicViperS"
artifact_type = "Function"

[header]
name = "SolAct_VolcanicViperS"
addr = 0x2525e0

[header.args]
