last_change = 2024-12-26T02:50:09.332678Z
addr = 0x251f30
size = 0x3b
name = "SolAct_ggxGrandViperDrop"
artifact_type = "Function"

[header]
name = "SolAct_ggxGrandViperDrop"
addr = 0x251f30

[header.args]
