last_change = 2024-12-26T02:50:09.332678Z
addr = 0x2509e0
size = 0x3b
name = "SolAct_AirBanditRevolver2"
artifact_type = "Function"

[header]
name = "SolAct_AirBanditRevolver2"
addr = 0x2509e0

[header.args]
