last_change = 2024-12-26T02:50:09.332678Z
addr = 0x250320
size = 0x42
name = "EXSolAct_AirGunflameDrop"
artifact_type = "Function"

[header]
name = "EXSolAct_AirGunflameDrop"
addr = 0x250320

[header.args]
