last_change = 2024-12-26T02:50:09.332678Z
addr = 0x250140
size = 0x46
name = "EXSolAct_BanditRevolverLand"
artifact_type = "Function"

[header]
name = "EXSolAct_BanditRevolverLand"
addr = 0x250140

[header.args]
