last_change = 2024-12-26T02:50:09.332678Z
addr = 0x251ee0
size = 0x46
name = "SolAct_ggxGrandViperLand"
artifact_type = "Function"

[header]
name = "SolAct_ggxGrandViperLand"
addr = 0x251ee0

[header.args]
