last_change = 2024-12-26T02:50:09.332678Z
addr = 0x250880
size = 0x43
name = "EXSolAct_TyrantRaveA_2"
artifact_type = "Function"

[header]
name = "EXSolAct_TyrantRaveA_2"
addr = 0x250880

[header.args]
