last_change = 2024-12-26T02:50:09.332678Z
addr = 0x252260
size = 0x5e
name = "SolAct_AirDIVolcanicViper"
artifact_type = "Function"

[header]
name = "SolAct_AirDIVolcanicViper"
addr = 0x252260

[header.args]
