last_change = 2024-12-26T02:50:09.332678Z
addr = 0x2532c0
size = 0x60
name = "SolAct_SuperVolcanicViperH"
artifact_type = "Function"

[header]
name = "SolAct_SuperVolcanicViperH"
addr = 0x2532c0

[header.args]
