last_change = 2024-12-26T02:50:09.332678Z
addr = 0x252530
size = 0x53
name = "SolAct_VolcanicViperH"
artifact_type = "Function"

[header]
name = "SolAct_VolcanicViperH"
addr = 0x252530

[header.args]
