last_change = 2024-12-26T02:50:09.332678Z
addr = 0x2523a0
size = 0x60
name = "SolAct_DVolcanicViper"
artifact_type = "Function"

[header]
name = "SolAct_DVolcanicViper"
addr = 0x2523a0

[header.args]
