last_change = 2024-12-26T02:50:09.332678Z
addr = 0x250370
size = 0x57
name = "EXSolAct_AirGunflameH_2"
artifact_type = "Function"

[header]
name = "EXSolAct_AirGunflameH_2"
addr = 0x250370

[header.args]
