last_change = 2024-12-26T02:50:09.332678Z
addr = 0x2506b0
size = 0x74
name = "EXSolAct_WildPunchGrab"
artifact_type = "Function"

[header]
name = "EXSolAct_WildPunchGrab"
addr = 0x2506b0

[header.args]
