last_change = 2024-12-26T02:50:09.332678Z
addr = 0x250b70
size = 0x66
name = "SolAct_EnterInstakillMode"
artifact_type = "Function"

[header]
name = "SolAct_EnterInstakillMode"
addr = 0x250b70

[header.args]
