last_change = 2024-12-26T02:50:09.332678Z
addr = 0x252590
size = 0x46
name = "SolAct_VolcanicViperLand"
artifact_type = "Function"

[header]
name = "SolAct_VolcanicViperLand"
addr = 0x252590

[header.args]
