last_change = 2024-12-26T02:50:09.332678Z
addr = 0x253390
size = 0x6b
name = "SolAct_AirVolcanicViperH"
artifact_type = "Function"

[header]
name = "SolAct_AirVolcanicViperH"
addr = 0x253390

[header.args]
