last_change = 2024-12-26T02:50:09.332678Z
addr = 0x250a20
size = 0x52
name = "SolAct_AirBanditRevolver1"
artifact_type = "Function"

[header]
name = "SolAct_AirBanditRevolver1"
addr = 0x250a20

[header.args]
