last_change = 2024-12-26T02:50:09.332678Z
addr = 0x251c10
size = 0x46
name = "SolAct_BanditBringerLand"
artifact_type = "Function"

[header]
name = "SolAct_BanditBringerLand"
addr = 0x251c10

[header.args]
