last_change = 2024-12-26T02:50:09.332678Z
addr = 0x250990
size = 0x4d
name = "SolAct_AirBanditRevolverLand"
artifact_type = "Function"

[header]
name = "SolAct_AirBanditRevolverLand"
addr = 0x250990

[header.args]
