last_change = 2024-12-26T02:50:09.332678Z
addr = 0x2aed20
size = 0xf
name = "af_DO_NOT_CHECK_DAMAGE"
artifact_type = "Function"

[header]
name = "af_DO_NOT_CHECK_DAMAGE"
addr = 0x2aed20

[header.args]
