last_change = 2024-12-26T02:50:09.332678Z
addr = 0x2aee80
size = 0x41
name = "af_PARENT_OFFSET_POS_X"
artifact_type = "Function"

[header]
name = "af_PARENT_OFFSET_POS_X"
addr = 0x2aee80

[header.args]
