last_change = 2024-12-26T02:50:09.332678Z
addr = 0x2ad2f0
size = 0x50
name = "DirectionDirectChange"
artifact_type = "Function"

[header]
name = "DirectionDirectChange"
addr = 0x2ad2f0

[header.args]
