last_change = 2024-12-26T02:50:09.332678Z
addr = 0x2aed30
size = 0xc
name = "af_DO_NOT_CHECK_ATTACK"
artifact_type = "Function"

[header]
name = "af_DO_NOT_CHECK_ATTACK"
addr = 0x2aed30

[header.args]
