last_change = 2024-12-26T02:50:09.332678Z
addr = 0x36e000
size = 0x20
name = "lpStartAddress_0076e000"
artifact_type = "Function"

[header]
name = "lpStartAddress_0076e000"
addr = 0x36e000

[header.args]
