last_change = 2024-12-26T02:50:09.332678Z
addr = 0x3a3387
size = 0x3c
name = "__startOneArgErrorHandling"
artifact_type = "Function"

[header]
name = "__startOneArgErrorHandling"
addr = 0x3a3387

[header.args]
