last_change = 2024-12-26T02:50:09.332678Z
addr = 0x3a42b0
size = 0x2e
name = "___libm_setusermatherr"
artifact_type = "Function"

[header]
name = "___libm_setusermatherr"
addr = 0x3a42b0

[header.args]
